# Generated by Django 3.2.1 on 2021-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0004_quiz_details_quiz_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_ans',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
