# Generated by Django 3.2.1 on 2021-05-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0005_question_correct_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_details',
            name='submission',
            field=models.CharField(default=-1, max_length=100000),
            preserve_default=False,
        ),
    ]
