# Generated by Django 3.2.1 on 2021-05-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0007_alter_quiz_details_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.CharField(blank=True, max_length=1000)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Submission_Set', to='API_Quiz.quiz_details')),
            ],
        ),
    ]
