# Generated by Django 3.2.1 on 2021-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0008_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_text',
            field=models.CharField(max_length=1000),
        ),
    ]
