# Generated by Django 3.2.1 on 2021-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0009_alter_submission_submission_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_id',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
