# Generated by Django 3.2.1 on 2021-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0012_auto_20210514_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isOpenText',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
