# Generated by Django 3.2.1 on 2021-05-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0015_question_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True),
        ),
    ]
