# Generated by Django 3.2.1 on 2021-05-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0016_alter_question_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='question_id',
            field=models.IntegerField(blank=True),
        ),
    ]
