# Generated by Django 3.2.1 on 2021-05-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0017_alter_submission_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='isOpenText',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
