# Generated by Django 3.2.1 on 2021-05-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0018_alter_question_isopentext'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='quiz_id',
            field=models.ForeignKey(default=63, on_delete=django.db.models.deletion.CASCADE, related_name='Quiz_ref_set', to='API_Quiz.quiz_details'),
            preserve_default=False,
        ),
    ]
