# Generated by Django 3.2.1 on 2021-05-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0019_submission_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quiz_ref_Set', to='API_Quiz.quiz_details'),
        ),
    ]
