# Generated by Django 3.2.1 on 2021-05-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Quiz', '0020_alter_submission_quiz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_details',
            name='submission',
        ),
    ]
